apiVersion: "app.redislabs.com/v1alpha1"
kind: "RedisEnterpriseCluster"
metadata:
  name: "demo1"
spec:
  nodes: 3
  persistentSpec:
    enabled: false # in order to allow multiple pods on the same node
    #volumeSize: "10Gi" # if you don't provide default is 5 times RAM size
    storageClassName: "redis-storage" # ! edit according to infrastructure
  username: "demo@redislabs.com"
  redisEnterpriseNodeResources:
    limits:
      cpu: "2000m"
      memory: 4Gi
    requests:
      cpu: "2000m"
      memory: 4Gi
  redisEnterpriseImageSpec:
    imagePullPolicy:  IfNotPresent
    Repository:       redislabs/redis
    versionTag:       5.4.6-18.rhel7-openshift
  redisEnterpriseServicesRiggerImageSpec:
    imagePullPolicy:  IfNotPresent
    repository:       redislabs/k8s-controller
    versionTag:       5.4.6-1186b.rhel7
  podAntiAffinity: # disable anti affinity to allow loading multiple pods on the same node
    RequiredDuringSchedulingIgnoredDuringExecution:
      namespaces:
      - default
