---
apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: redis-storage-0
spec:
  storageClassName: redis-storage
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  capacity:
    storage: 2000Gi
  hostPath:
    path: /mnt/data/redis-0
    type: ""
  persistentVolumeReclaimPolicy: Retain
