apiVersion: "app.redislabs.com/v1"
kind: "RedisEnterpriseCluster"
metadata:
  name: "demo1"
spec:
  nodes: 3
  persistentSpec:
    enabled: true
    storageClassName: "redis-storage" # ! edit according to infrastructure
  uiServiceType: LoadBalancer
  username: "demo@redislabs.com"
  redisEnterpriseNodeResources:
    limits:
      cpu: "4000m"
      memory: 4Gi
    requests:
      cpu: "4000m"
      memory: 4Gi
  redisEnterpriseImageSpec:
    imagePullPolicy:  IfNotPresent
    repository:       redislabs/redis
    versionTag:       5.4.10-22.rhel7-openshift
  redisEnterpriseServicesRiggerImageSpec:
    imagePullPolicy:  IfNotPresent
    repository:       redislabs/k8s-controller
    versionTag:       5.4.10-8b.rhel77
  podAntiAffinity: # disable anti affinity to allow loading multiple pods on the same node
    RequiredDuringSchedulingIgnoredDuringExecution:
      namespaces:
      - default
