apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: redis-vol
spec:
  storageClassName: redis-storage
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  capacity:
    storage: 2000Gi
  hostPath:
    path: /mnt/data/vol99
    type: ""
  persistentVolumeReclaimPolicy: Retain
